title: Specialization Dossier: Map of the Ecological Landscape of LIS Work
description: Created by Group 6: Anna Friedman, Diana Naughton, Emma Hughes, Sam Garcia
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
